"""
Deterministic explanation generator for JobGuard.
All explanatory text is generated by pure Python string templates.
No AI, no Claude, no OpenAI, no HuggingFace. Zero AI services.
"""

from typing import List, Dict, Optional


FEATURE_LOOKUP = {
    # TF-IDF features
    "tfidf__work": "emphasis on work-related terminology in the posting text",
    "tfidf__home": "references to home-based or work-from-home arrangements",
    "tfidf__earn": "mentions of earning potential or income promises",
    "tfidf__apply": "frequency of application-related language",
    "tfidf__experience": "references to experience requirements in the text",
    "tfidf__skill": "mentions of skill requirements",
    "tfidf__team": "references to team or collaborative work environment",
    "tfidf__company": "frequency of company-related references",
    "tfidf__position": "mentions of position-specific details",
    "tfidf__salary": "references to salary or compensation details",
    "tfidf__require": "frequency of requirement-related language",
    "tfidf__opportunity": "use of opportunity-related promotional language",
    "tfidf__job": "general job-related terminology frequency",
    "tfidf__benefit": "mentions of benefits or perks",
    "tfidf__qualification": "references to qualifications needed",
    "tfidf__training": "mentions of training programs or onboarding",
    "tfidf__data": "references to data-related responsibilities",
    "tfidf__manage": "management-related terminology in the posting",
    "tfidf__great": "use of superlative or promotional adjectives",
    "tfidf__career": "career advancement or growth language",
    "tfidf__flexible": "emphasis on flexible working arrangements",
    "tfidf__income": "direct references to income or money",
    "tfidf__hire": "hiring urgency or recruitment language",
    "tfidf__immediate": "urgency indicators like immediate start",
    "tfidf__part": "references to part-time or partial employment",
    "tfidf__customer": "customer service or client-facing language",
    "tfidf__drive": "references to driving or travel requirements",
    "tfidf__travel": "travel requirement mentions in the posting",
    "tfidf__worldwide": "claims of worldwide or global operations",
    "tfidf__weekly": "weekly payment or schedule references",
    "tfidf__commission": "commission-based compensation language",
    "tfidf__bonus": "bonus or incentive payment references",
    "tfidf__urgent": "urgency-driven language patterns",
    "tfidf__online": "references to online or internet-based work",
    "tfidf__simple": "descriptions of work as simple or easy",
    "tfidf__paid": "paid training or upfront payment language",
    "tfidf__hour": "hourly rate or per-hour compensation mentions",
    "tfidf__free": "references to free training or no-cost elements",
    "tfidf__register": "registration or sign-up language",
    "tfidf__click": "click-based action language patterns",
    "tfidf__send": "instructions to send personal information",
    "tfidf__profile": "profile creation or personal data requests",
    "tfidf__fast": "fast or quick result promises",
    "tfidf__entry": "entry-level or no-barrier-to-entry language",
    "tfidf__no_experience": "explicit mentions of no experience needed",
    "tfidf__resume": "resume or CV submission language",
    "tfidf__interview": "interview process mentions",
    "tfidf__full_time": "full-time employment references in text",
    "tfidf__remote": "remote work or telecommuting language",
    "tfidf__client": "client relationship or servicing language",
    "tfidf__project": "project-based work terminology",
    "tfidf__support": "support role or assistance language",
    "tfidf__service": "service-oriented role descriptions",
    "tfidf__marketing": "marketing-related terminology",
    "tfidf__sale": "sales-related language in the posting",
    "tfidf__health": "health benefits or healthcare mentions",
    "tfidf__insurance": "insurance or coverage benefit mentions",
    "tfidf__education": "education requirement or background references",
    "tfidf__degree": "degree requirement mentions",
    "tfidf__year": "years of experience references",
    "tfidf__excellent": "use of excellent or exceptional descriptors",
    "tfidf__dynamic": "dynamic or fast-paced environment language",
    "tfidf__grow": "growth opportunity language",
    "tfidf__start": "start date or immediate beginning language",
    "tfidf__money": "direct money or financial references",
    "tfidf__payment": "payment-related terms in the posting",
    "tfidf__guarantee": "guarantee or promise language",
    "tfidf__unlimited": "unlimited earning or potential claims",
    "tfidf__investment": "investment or financial opportunity language",
    "tfidf__fee": "fee or payment requirement references",
    "tfidf__account": "account creation or financial account language",
    "tfidf__processing": "processing or data entry task descriptions",
    # Binary features
    "binary__has_company_logo": "absence of a company logo in the posting",
    "binary__has_questions": "absence of structured screening questions",
    "binary__telecommuting": "remote work designation",
    "has_company_logo": "absence of a company logo in the posting",
    "has_questions": "absence of structured screening questions",
    "telecommuting": "remote work designation",
    # OneHot employment type features
    "onehot__employment_type_Full-time": "full-time employment classification",
    "onehot__employment_type_Part-time": "part-time employment classification",
    "onehot__employment_type_Contract": "contract-based employment classification",
    "onehot__employment_type_Temporary": "temporary employment classification",
    "onehot__employment_type_Other": "non-standard employment type classification",
    # OneHot required experience features
    "onehot__required_experience_Entry level": "entry-level experience requirement",
    "onehot__required_experience_Mid-Senior level": "mid-senior level experience requirement",
    "onehot__required_experience_Associate": "associate-level experience requirement",
    "onehot__required_experience_Executive": "executive-level experience requirement",
    "onehot__required_experience_Director": "director-level experience requirement",
    "onehot__required_experience_Internship": "internship experience level",
    "onehot__required_experience_Not Applicable": "unspecified experience requirement",
    # OneHot required education features
    "onehot__required_education_Bachelor's Degree": "bachelor's degree requirement",
    "onehot__required_education_Master's Degree": "master's degree requirement",
    "onehot__required_education_High School or equivalent": "high school education requirement",
    "onehot__required_education_Associate Degree": "associate degree requirement",
    "onehot__required_education_Unspecified": "unspecified education requirement",
    "onehot__required_education_Some College Coursework Completed": "some college coursework requirement",
    "onehot__required_education_Certification": "certification requirement",
    "onehot__required_education_Doctorate": "doctorate degree requirement",
    "onehot__required_education_Vocational": "vocational education requirement",
    "onehot__required_education_Vocational - Degree": "vocational degree requirement",
    "onehot__required_education_Vocational - HS Diploma": "vocational high school diploma requirement",
    "onehot__required_education_Professional": "professional degree requirement",
    "onehot__required_education_Some High School Coursework": "some high school coursework requirement",
    # OneHot industry features (top 15)
    "onehot__industry_Information Technology and Services": "information technology industry classification",
    "onehot__industry_Computer Software": "computer software industry classification",
    "onehot__industry_Marketing and Advertising": "marketing and advertising industry",
    "onehot__industry_Hospital & Health Care": "healthcare industry classification",
    "onehot__industry_Financial Services": "financial services industry classification",
    "onehot__industry_Staffing and Recruiting": "staffing and recruiting industry",
    "onehot__industry_Internet": "internet industry classification",
    "onehot__industry_Oil & Energy": "oil and energy industry classification",
    "onehot__industry_Management Consulting": "management consulting industry",
    "onehot__industry_Telecommunications": "telecommunications industry classification",
    "onehot__industry_Consumer Services": "consumer services industry classification",
    "onehot__industry_Education Management": "education management industry",
    "onehot__industry_Retail": "retail industry classification",
    "onehot__industry_Banking": "banking industry classification",
    "onehot__industry_Automotive": "automotive industry classification",
    # OneHot function features (top 15)
    "onehot__function_Sales": "sales function classification",
    "onehot__function_Information Technology": "information technology function",
    "onehot__function_Engineering": "engineering function classification",
    "onehot__function_Marketing": "marketing function classification",
    "onehot__function_Customer Service": "customer service function classification",
    "onehot__function_Administrative": "administrative function classification",
    "onehot__function_Management": "management function classification",
    "onehot__function_Education": "education function classification",
    "onehot__function_Health Care Provider": "healthcare provider function",
    "onehot__function_Design": "design function classification",
    "onehot__function_Human Resources": "human resources function classification",
    "onehot__function_Business Development": "business development function",
    "onehot__function_Accounting/Auditing": "accounting/auditing function",
    "onehot__function_Writing/Editing": "writing/editing function classification",
    "onehot__function_Other": "unspecified function classification",
}


def _lookup_feature(name: str) -> str:
    """Look up a human-readable description for a feature name."""
    if name in FEATURE_LOOKUP:
        return FEATURE_LOOKUP[name]
    # Try partial matching for tfidf features
    for key, desc in FEATURE_LOOKUP.items():
        if name.startswith("tfidf__") and key.startswith("tfidf__"):
            if name.split("__", 1)[1] == key.split("__", 1)[1]:
                return desc
    # Fallback: format the raw name
    clean = name.replace("tfidf__", "").replace("onehot__", "").replace("binary__", "")
    clean = clean.replace("_", " ")
    return f"the feature '{clean}'"


def generate_explanation(
    verdict: str,
    fraud_probability: float,
    risk_scores: Dict[str, int],
    top_shap_features: List[Dict],
    red_flags: List[str],
    job_title: str,
    company_name: str,
) -> str:
    """
    Generate a 3-paragraph deterministic explanation.
    No randomness, no AI. Pure template logic.
    """
    pct = round(fraud_probability * 100, 1)

    # PARAGRAPH 1 - select by fraud_probability
    if fraud_probability < 0.20:
        p1 = (
            f"Our model evaluated the posting for {job_title} at {company_name} with strong confidence "
            f"and found it consistent with legitimate job listings. The fraud probability score of {pct}% "
            f"places this firmly within the range of verified genuine opportunities across our "
            f"17,880-sample training dataset."
        )
    elif fraud_probability < 0.35:
        p1 = (
            f"The posting for {job_title} at {company_name} presents as largely legitimate, though a small "
            f"cluster of signals warrants closer inspection. The fraud probability of {pct}% is low but not "
            f"negligible \u2014 we recommend standard verification steps before proceeding."
        )
    elif fraud_probability < 0.60:
        p1 = (
            f"Our analysis of {job_title} at {company_name} returned a suspicious classification with a "
            f"fraud probability of {pct}%. Several features in this posting are inconsistent with patterns "
            f"found in verified legitimate listings across our 17,880-sample training dataset."
        )
    elif fraud_probability < 0.80:
        p1 = (
            f"This posting for {job_title} at {company_name} shows a high likelihood of being fraudulent, "
            f"with a fraud probability score of {pct}%. Multiple signals align with patterns that our "
            f"RandomForest model consistently associates with deceptive job postings."
        )
    else:
        p1 = (
            f"Our model has flagged the posting for {job_title} at {company_name} as highly likely "
            f"fraudulent with {pct}% confidence. The combination of features detected matches known fraud "
            f"patterns across our entire training dataset."
        )

    # PARAGRAPH 2 - signals from SHAP features
    fraud_features = [f for f in top_shap_features if f.get("direction") == "fraud"]
    top3_fraud = fraud_features[:3]

    if len(top3_fraud) >= 3:
        desc1 = _lookup_feature(top3_fraud[0]["name"])
        desc2 = _lookup_feature(top3_fraud[1]["name"])
        desc3 = _lookup_feature(top3_fraud[2]["name"])
        p2 = (
            f"The most influential signals driving this classification were: {desc1}, "
            f"{desc2}, and {desc3}."
        )
    elif len(top3_fraud) == 2:
        desc1 = _lookup_feature(top3_fraud[0]["name"])
        desc2 = _lookup_feature(top3_fraud[1]["name"])
        p2 = f"The most influential signals driving this classification were: {desc1} and {desc2}."
    elif len(top3_fraud) == 1:
        desc1 = _lookup_feature(top3_fraud[0]["name"])
        p2 = f"The most influential signal driving this classification was: {desc1}."
    else:
        p2 = "No strong fraud-direction signals were identified among the top features."

    # Conditional appends based on risk scores
    company_signals = risk_scores.get("company_signals", 100)
    text_quality = risk_scores.get("text_quality", 100)
    offer_realism = risk_scores.get("offer_realism", 100)

    if company_signals < 40:
        p2 += (
            " The posting lacked standard employer verification markers such as a company logo and "
            "structured screening questions, both of which are present in the overwhelming majority "
            "of legitimate postings."
        )
    if text_quality < 40:
        p2 += (
            " The language patterns within the posting text showed characteristics commonly associated "
            "with templated or copy-pasted fraudulent content."
        )
    if offer_realism < 40:
        p2 += (
            " The stated employment terms appear inconsistent with typical verified postings for this "
            "role type and experience level."
        )

    # PARAGRAPH 3 - red flags + closing
    num_flags = len(red_flags)
    if num_flags == 0:
        p3 = "No additional red flags were reported."
    elif num_flags == 1:
        p3 = f"One red flag was reported: {red_flags[0]}."
    else:
        p3 = f"{num_flags} red flags were reported, including {red_flags[0]} and {red_flags[1]}."

    # Closing by verdict
    if verdict == "REAL":
        p3 += (
            " We recommend proceeding normally while following standard precautions \u2014 verify the "
            "company independently and never share sensitive documents until legitimacy is confirmed."
        )
    elif verdict == "SUSPICIOUS":
        p3 += (
            " Proceed with significant caution. Verify the company\u2019s web presence, confirm the "
            "contact email domain, and do not provide financial or identity documents until fully established."
        )
    elif verdict == "FAKE":
        p3 += (
            " We strongly advise against engaging further. Do not provide personal information. "
            "Consider reporting this posting to your country\u2019s consumer protection agency."
        )

    return f"{p1}\n\n{p2}\n\n{p3}"
